<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('bukus')->insert([
            [
                'judul'          => 'Laskar Pelangi',
                'pengarang'      => 'Andrea Hirata',
                'kategori'       => 'Fiksi',
                'penerbit'       => 'Bentang Pustaka',
                'tahun_terbit'   => 2005,
                'isbn'           => '978-979-1062-79-9',
                'jumlah_halaman' => 534,
                'deskripsi'      => 'Novel inspiratif tentang perjuangan anak-anak Belitung dalam mengejar impian di tengah keterbatasan.',
                'cover_color'    => 'oklch(62% .13 220)',
                'stok'           => 3,
                'stok_tersedia'  => 3,
                'rating'         => 4.8,
                'rating_count'   => 234,
                'lokasi_rak'     => 'Rak A-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Bumi Manusia',
                'pengarang'      => 'Pramoedya Ananta Toer',
                'kategori'       => 'Sastra',
                'penerbit'       => 'Hasta Mitra',
                'tahun_terbit'   => 1980,
                'isbn'           => '978-602-433-017-8',
                'jumlah_halaman' => 421,
                'deskripsi'      => 'Kisah Minke, pribumi terpelajar di era kolonial Belanda yang melawan penindasan dengan pena.',
                'cover_color'    => 'oklch(58% .10 55)',
                'stok'           => 2,
                'stok_tersedia'  => 2,
                'rating'         => 4.9,
                'rating_count'   => 312,
                'lokasi_rak'     => 'Rak A-2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Kimia Dasar',
                'pengarang'      => 'Raymond Chang',
                'kategori'       => 'Sains',
                'penerbit'       => 'McGraw-Hill',
                'tahun_terbit'   => 2010,
                'isbn'           => '978-0-07-351109-2',
                'jumlah_halaman' => 892,
                'deskripsi'      => 'Buku teks kimia dasar komprehensif untuk tingkat menengah dan perguruan tinggi.',
                'cover_color'    => 'oklch(55% .13 145)',
                'stok'           => 2,
                'stok_tersedia'  => 0,
                'rating'         => 4.3,
                'rating_count'   => 89,
                'lokasi_rak'     => 'Rak B-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Matematika SMK Kelas XII',
                'pengarang'      => 'Sukino',
                'kategori'       => 'Pelajaran',
                'penerbit'       => 'Erlangga',
                'tahun_terbit'   => 2019,
                'isbn'           => '978-602-282-123-4',
                'jumlah_halaman' => 320,
                'deskripsi'      => 'Buku pelajaran matematika SMK kelas XII mencakup integral dan statistika.',
                'cover_color'    => 'oklch(58% .14 265)',
                'stok'           => 5,
                'stok_tersedia'  => 5,
                'rating'         => 4.1,
                'rating_count'   => 67,
                'lokasi_rak'     => 'Rak C-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Atomic Habits',
                'pengarang'      => 'James Clear',
                'kategori'       => 'Pengembangan Diri',
                'penerbit'       => 'Avery',
                'tahun_terbit'   => 2018,
                'isbn'           => '978-0-7352-1129-2',
                'jumlah_halaman' => 306,
                'deskripsi'      => 'Panduan praktis membangun kebiasaan baik dan menghilangkan kebiasaan buruk secara ilmiah.',
                'cover_color'    => 'oklch(62% .11 30)',
                'stok'           => 3,
                'stok_tersedia'  => 3,
                'rating'         => 4.7,
                'rating_count'   => 198,
                'lokasi_rak'     => 'Rak D-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Harry Potter & Batu Bertuah',
                'pengarang'      => 'J.K. Rowling',
                'kategori'       => 'Fiksi',
                'penerbit'       => 'Gramedia',
                'tahun_terbit'   => 1997,
                'isbn'           => '978-979-22-2765-4',
                'jumlah_halaman' => 309,
                'deskripsi'      => 'Petualangan Harry Potter di sekolah sihir Hogwarts melawan kekuatan jahat.',
                'cover_color'    => 'oklch(55% .13 310)',
                'stok'           => 2,
                'stok_tersedia'  => 0,
                'rating'         => 4.9,
                'rating_count'   => 445,
                'lokasi_rak'     => 'Rak A-3',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Sejarah Indonesia Modern',
                'pengarang'      => 'M.C. Ricklefs',
                'kategori'       => 'Sejarah',
                'penerbit'       => 'Serambi',
                'tahun_terbit'   => 2008,
                'isbn'           => '978-602-7741-14-0',
                'jumlah_halaman' => 674,
                'deskripsi'      => 'Analisis mendalam sejarah Indonesia dari abad ke-14 hingga era reformasi.',
                'cover_color'    => 'oklch(58% .10 70)',
                'stok'           => 2,
                'stok_tersedia'  => 2,
                'rating'         => 4.5,
                'rating_count'   => 112,
                'lokasi_rak'     => 'Rak E-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Pemrograman Python',
                'pengarang'      => 'Eric Matthes',
                'kategori'       => 'Teknologi',
                'penerbit'       => 'No Starch Press',
                'tahun_terbit'   => 2019,
                'isbn'           => '978-1-59327-928-8',
                'jumlah_halaman' => 544,
                'deskripsi'      => 'Panduan belajar Python dari dasar hingga mahir dengan proyek nyata.',
                'cover_color'    => 'oklch(60% .13 175)',
                'stok'           => 3,
                'stok_tersedia'  => 3,
                'rating'         => 4.6,
                'rating_count'   => 156,
                'lokasi_rak'     => 'Rak F-1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Filosofi Teras',
                'pengarang'      => 'Henry Manampiring',
                'kategori'       => 'Pengembangan Diri',
                'penerbit'       => 'Kompas',
                'tahun_terbit'   => 2019,
                'isbn'           => '978-602-03-9462-7',
                'jumlah_halaman' => 304,
                'deskripsi'      => 'Penerapan filsafat Stoa untuk menghadapi berbagai persoalan hidup modern.',
                'cover_color'    => 'oklch(63% .08 65)',
                'stok'           => 3,
                'stok_tersedia'  => 3,
                'rating'         => 4.6,
                'rating_count'   => 267,
                'lokasi_rak'     => 'Rak D-2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Fisika Untuk SMA/SMK',
                'pengarang'      => 'Marthen Kanginan',
                'kategori'       => 'Pelajaran',
                'penerbit'       => 'Erlangga',
                'tahun_terbit'   => 2020,
                'isbn'           => '978-602-282-456-3',
                'jumlah_halaman' => 480,
                'deskripsi'      => 'Buku pelajaran fisika lengkap untuk siswa SMA/SMK dengan soal dan pembahasan.',
                'cover_color'    => 'oklch(58% .11 195)',
                'stok'           => 4,
                'stok_tersedia'  => 0,
                'rating'         => 4.4,
                'rating_count'   => 78,
                'lokasi_rak'     => 'Rak C-2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Clean Code',
                'pengarang'      => 'Robert C. Martin',
                'kategori'       => 'Teknologi',
                'penerbit'       => 'Prentice Hall',
                'tahun_terbit'   => 2008,
                'isbn'           => '978-0-13-235088-4',
                'jumlah_halaman' => 431,
                'deskripsi'      => 'Panduan menulis kode bersih, mudah dibaca dan dipelihara untuk developer profesional.',
                'cover_color'    => 'oklch(28% .03 80)',
                'stok'           => 2,
                'stok_tersedia'  => 2,
                'rating'         => 4.8,
                'rating_count'   => 189,
                'lokasi_rak'     => 'Rak F-2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'judul'          => 'Seni Berbicara di Depan Umum',
                'pengarang'      => 'Dale Carnegie',
                'kategori'       => 'Pengembangan Diri',
                'penerbit'       => 'Gramedia',
                'tahun_terbit'   => 2016,
                'isbn'           => '978-602-02-5678-3',
                'jumlah_halaman' => 278,
                'deskripsi'      => 'Teknik dan strategi komunikasi efektif untuk tampil percaya diri di hadapan publik.',
                'cover_color'    => 'oklch(60% .12 15)',
                'stok'           => 2,
                'stok_tersedia'  => 2,
                'rating'         => 4.3,
                'rating_count'   => 143,
                'lokasi_rak'     => 'Rak D-3',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
